services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: indusio_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: indusio_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
  db:
    image: postgres:15
    container_name: indusio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahmedahmed12345
      POSTGRES_DB: ppp
    ports:
      - "5432:5432"
